version: '3.1'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=name
      - POSTGRES_PASSWORD=pass